INSERT INTO site_content (key, value_en, value_he, page, section) VALUES
('search.price_min', '0', '0', 'global', 'search'),
('search.price_max', '20000000', '20000000', 'global', 'search'),
('search.price_step', '50000', '50000', 'global', 'search'),
('guide.home.title', 'Planning to Buy in Zichron Yaakov?', 'שוקלים לקנות בית בזכרון יעקב?', 'home', 'guide'),
('guide.home.hook', 'Start with the Zichron Yaakov Buyer Blueprint — a practical guide created for English-speaking buyers researching property in the Moshava.', 'רוב האנשים שמגיעים לחפש בית בזכרון יעקב לא מכירים את ההבדלים האמיתיים בין השכונות — וזה יכול לעלות מאות אלפי שקלים.', 'home', 'guide'),
('guide.home.intro', 'A practical guide to help you navigate the local market with confidence.', 'לכן יצרנו את המדריך לרוכשי בתים בזכרון יעקב.', 'home', 'guide'),
('guide.home.cta_primary', 'Download the Guide', 'הורדת המדריך', 'home', 'guide'),
('guide.home.cta_secondary', 'Get the Zichron Buyer Blueprint', 'שלחו לי את המדריך בוואטסאפ', 'home', 'guide'),
('guide.home.trust_line', 'Sent instantly via WhatsApp.', 'נשלח מיידית בוואטסאפ.', 'home', 'guide'),
('guide.home.positioning', 'This guide is shared privately with serious buyers exploring property in Zichron Yaakov.', 'המדריך נשלח באופן פרטי למי שבוחן קנייה בזכרון יעקב.', 'home', 'guide'),
('guide.home.bullet_1', 'Real neighborhood price data', 'מחירי בתים אמיתיים לפי שכונות בזכרון יעקב', 'home', 'guide'),
('guide.home.bullet_2', 'Verified market transactions', 'עסקאות שבוצעו בפועל ומה באמת משלמים היום', 'home', 'guide'),
('guide.home.bullet_3', 'Investment insights', 'איפה מתרכזת האוכלוסייה החזקה במושבה', 'home', 'guide'),
('guide.home.bullet_4', 'Neighborhood comparison', 'הבדלים בין השכונות ומה מתאים למשפחות', 'home', 'guide'),
('guide.home.bullet_5', 'Fast-selling homes', 'מה גורם לבתים טובים להימכר מהר', 'home', 'guide'),
('guide.home.bullet_6', 'Off-market opportunities', 'איך לזהות הזדמנות לפני שהיא מגיעה ללוחות', 'home', 'guide'),
('guide.home.bullet_7', 'Common buyer mistakes', 'טעויות נפוצות שקונים עושים בזכרון יעקב ואיך להימנע מהן', 'home', 'guide'),
('guide.home.bullet_8', 'Step-by-step buying roadmap', 'ניתוח שוק מקומי שלא תמצאו ביד2', 'home', 'guide'),
('whatsapp.hero_message', 'Hi, I''d like to receive the Zichron Yaakov Buyer Blueprint.', 'היי, אשמח לקבל את מדריך הקנייה לזכרון יעקב.', 'global', 'whatsapp'),
('whatsapp.guide_message', 'Hi, I''d like to receive the Zichron Yaakov Buyer Blueprint.', 'היי, אשמח לקבל את מדריך הקנייה לזכרון יעקב.', 'global', 'whatsapp'),
('whatsapp.closing_message', 'Hi Hagit, I''m looking at homes in Zichron Yaakov and would love to learn more. Could you also send me the buying guide?', 'היי חגית, אני מחפש/ת בית בזכרון יעקב ואשמח לשמוע עוד. אפשר גם לשלוח לי את המדריך?', 'global', 'whatsapp'),
('whatsapp.closing_guide_message', 'Hi Hagit, I would love to receive the guide about buying property in Zichron Yaakov.', 'היי חגית, אשמח לקבל את המדריך על רכישת נכס בזכרון יעקב.', 'global', 'whatsapp'),
('whatsapp.team_message', 'Hi, I''d like to learn more about homes in Zichron Yaakov.', 'היי, אשמח לשמוע על בתים בזכרון יעקב.', 'global', 'whatsapp'),
('whatsapp.offmarket_message', 'Hi, I''m interested in off-market homes in Zichron Yaakov.', 'היי, מתעניין/ת בנכסים שלא פורסמו בזכרון יעקב.', 'global', 'whatsapp'),
('team.title', 'Who''s Behind Spirit Real Estate', 'מי עומד מאחורי Spirit Real Estate', 'home', 'team'),
('team.text', 'Behind every great property is deep market knowledge, local relationships and the ability to recognize the right opportunity at the right time.\nWe work with buyers who are not just looking for a home, but for the right decision in the right place and under the right conditions.', 'מאחורי כל נכס טוב יש היכרות עמוקה עם השוק, קשרים מקומיים ויכולת לזהות הזדמנות בזמן.\nאנחנו מלווים קונים שמחפשים לא רק בית — אלא גם החלטה נכונה, במקום הנכון ובתנאים הנכונים.', 'home', 'team'),
('team.trust_line', 'Over 288 families have already worked with us to find the right home in Zichron Yaakov.', 'מעל 288 משפחות כבר נעזרו בנו כדי למצוא את הבית הנכון בזכרון יעקב.', 'home', 'team'),
('team.cta', 'Message Us on WhatsApp', 'דברו איתנו בוואטסאפ', 'home', 'team'),
('home.offmarket.title', 'What most buyers don''t know:', 'משהו שרוב הקונים לא יודעים:', 'home', 'offmarket'),
('home.offmarket.text_1', 'Some of our best opportunities are sold quietly and never reach public listing sites.', 'חלק מהבתים הטובים ביותר בזכרון יעקב נמכרים עוד לפני שהם מגיעים ללוחות.', 'home', 'offmarket'),
('home.offmarket.text_2', 'Message us to access off-market homes in Zichron Yaakov.', 'שלחו הודעה ונשלח לכם הזדמנויות חדשות כשהן מגיעות לשוק.', 'home', 'offmarket')
ON CONFLICT (key) DO NOTHING;