INSERT INTO public.site_content (key, page, section, value_he, value_en) VALUES
('home.testimonials.eyebrow', 'home', 'testimonials', 'מה אומרים הלקוחות שלנו', 'What our clients say'),
('home.testimonials.title', 'home', 'testimonials', 'משפחות שכבר מצאו את הבית שלהן בזכרון', 'Families who already found their home in Zichron'),
('home.testimonials.subtitle', 'home', 'testimonials', 'לקוחות פרטיים מהארץ ומחו"ל שליווינו עד למפתח', 'Private clients from Israel and abroad we guided to the keys'),
('home.testimonials.metric_1_value', 'home', 'testimonials', '80+', '80+'),
('home.testimonials.metric_1_label', 'home', 'testimonials', 'משפחות מאושרות', 'happy families'),
('home.testimonials.metric_2_value', 'home', 'testimonials', '5+', '5+'),
('home.testimonials.metric_2_label', 'home', 'testimonials', 'שנים בזכרון יעקב', 'years in Zichron Yaakov'),
('home.testimonials.metric_3_value', 'home', 'testimonials', '4', '4'),
('home.testimonials.metric_3_label', 'home', 'testimonials', 'שפות ליווי', 'languages of service'),
('home.testimonials.verified_label', 'home', 'testimonials', 'לקוח מאומת', 'Verified client'),
('home.testimonials.featured_badge', 'home', 'testimonials', 'סיפור מומלץ', 'Featured story'),
('home.testimonials.quote_1', 'home', 'testimonials',
  'קנייה מארה"ב הרגישה מורכבת בהתחלה. ספיריט הפכו את כל התהליך לברור, רגוע ומנוהל היטב מההתחלה ועד הסוף.',
  'Buying from the US felt overwhelming at first. Spirit Real Estate made the entire process clear, calm, and well managed from start to finish.'),
('home.testimonials.author_1', 'home', 'testimonials', 'דיוויד ושרה מ.', 'David & Sarah M.'),
('home.testimonials.context_1', 'home', 'testimonials', 'וילה ברחוב הנדיב · ניו יורק · 2024', 'Villa on HaNadiv St · New York · 2024'),
('home.testimonials.quote_2', 'home', 'testimonials',
  'הרגשנו שמישהו באמת מייצג אותנו מקומית. התקשורת הייתה שקופה לאורך כל הדרך, ותמיד ידענו מה קורה.',
  'We felt someone was truly representing us locally. Communication was transparent throughout, and we always knew what was happening.'),
('home.testimonials.author_2', 'home', 'testimonials', 'מייקל ר.', 'Michael R.'),
('home.testimonials.context_2', 'home', 'testimonials', 'דירת פנטהאוז · טורונטו · 2024', 'Penthouse apartment · Toronto · 2024'),
('home.testimonials.quote_3', 'home', 'testimonials',
  'הנוכחות המקומית עשתה את כל ההבדל. גם מרחוק הרגשנו ביטחון מלא שאנחנו מקבלים את ההחלטה הנכונה.',
  'The local presence made all the difference. Even from abroad, we felt fully confident we were making the right decision.'),
('home.testimonials.author_3', 'home', 'testimonials', 'ג''ונתן וליסה ב.', 'Jonathan & Lisa B.'),
('home.testimonials.context_3', 'home', 'testimonials', 'בית קרקע במושבה · לונדון · 2024', 'House in the Moshava · London · 2024'),
('home.testimonials.quote_4', 'home', 'testimonials',
  'ספיריט ליוו אותנו בכל צעד משפטי ולוגיסטי. אף פעם לא הרגשנו לבד בתהליך.',
  'Spirit guided us through every legal and logistical step. We never felt alone in the process.'),
('home.testimonials.author_4', 'home', 'testimonials', 'רחל ודניאל ק.', 'Rachel & Daniel K.'),
('home.testimonials.context_4', 'home', 'testimonials', 'וילה עם נוף לים · לוס אנג''לס · 2023', 'Sea-view villa · Los Angeles · 2023'),
('home.testimonials.quote_5', 'home', 'testimonials',
  'מקצועיים, דיסקרטיים ובאמת מושקעים במציאת הבית הנכון למשפחה שלנו. ממליצים בחום.',
  'Professional, discreet, and genuinely invested in finding the right home for our family. Highly recommend.'),
('home.testimonials.author_5', 'home', 'testimonials', 'יעל ומארק ס.', 'Yael & Marc S.'),
('home.testimonials.context_5', 'home', 'testimonials', 'בית בוטיק במרכז · פריז · 2024', 'Boutique home in the center · Paris · 2024'),
('home.testimonials.cta_text', 'home', 'testimonials',
  'מוכנים להיות הסיפור הבא שלנו?',
  'Ready to be our next story?'),
('home.testimonials.cta_button', 'home', 'testimonials',
  'דברו איתנו',
  'Talk to us'),
('home.trust_strip.metric_1_value', 'home', 'trust_strip', '80+', '80+'),
('home.trust_strip.metric_1_label', 'home', 'trust_strip', 'משפחות בחרו בספיריט', 'families chose Spirit'),
('home.trust_strip.metric_2_value', 'home', 'trust_strip', '5+', '5+'),
('home.trust_strip.metric_2_label', 'home', 'trust_strip', 'שנים בזכרון יעקב', 'years in Zichron Yaakov'),
('home.trust_strip.metric_3_value', 'home', 'trust_strip', '100%', '100%'),
('home.trust_strip.metric_3_label', 'home', 'trust_strip', 'ייצוג הקונה בלבד', 'buyer-side only'),
('home.trust_strip.tagline', 'home', 'trust_strip',
  'בוטיק נדל"ן פרטי · ליווי אישי בעברית, אנגלית, צרפתית ורוסית',
  'Private real-estate boutique · Personal service in English, Hebrew, French and Russian')
ON CONFLICT (key) DO UPDATE
  SET value_he = EXCLUDED.value_he,
      value_en = EXCLUDED.value_en,
      page = EXCLUDED.page,
      section = EXCLUDED.section,
      updated_at = now();